package com.example.speakerapp.ui.theme

import androidx.compose.ui.graphics.Color

// Teal Sentinel - PRD Colors
val md_theme_light_primary = Color(0xFF004650)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF135F6B)
val md_theme_light_onPrimaryContainer = Color(0xFF95D6E4)
val md_theme_light_secondary = Color(0xFF4A6267)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFCDE7ED)
val md_theme_light_onSecondaryContainer = Color(0xFF50686D)
val md_theme_light_tertiary = Color(0xFF004A0F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF006518)
val md_theme_light_onTertiaryContainer = Color(0xFF88E083)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFF6FAFA)
val md_theme_light_onBackground = Color(0xFF181C1D)
val md_theme_light_surface = Color(0xFFF6FAFA)
val md_theme_light_onSurface = Color(0xFF181C1D)
val md_theme_light_surfaceVariant = Color(0xFFDFE3E3)
val md_theme_light_onSurfaceVariant = Color(0xFF3F4949)
val md_theme_light_outline = Color(0xFF6F7979)
val md_theme_light_outlineVariant = Color(0xFFBEC8C9)
val md_theme_light_inverseSurface = Color(0xFF2C3132)
val md_theme_light_inverseOnSurface = Color(0xFFEDF1F1)
val md_theme_light_inversePrimary = Color(0xFF90D1DF)

// Additional Surface Tones from PRD
val surface_bright = Color(0xFFF6FAFA)
val surface_dim = Color(0xFFD7DBDB)
val surface_container_lowest = Color(0xFFFFFFFF)
val surface_container_low = Color(0xFFF0F4F4)
val surface_container = Color(0xFFEBEFEF)
val surface_container_high = Color(0xFFE5E9E9)
val surface_container_highest = Color(0xFFDFE3E3)

// Fixed Tones
val primary_fixed = Color(0xFFACEDFB)
val primary_fixed_dim = Color(0xFF90D1DF)
val on_primary_fixed = Color(0xFF001F25)
val on_primary_fixed_variant = Color(0xFF004E59)

val secondary_fixed = Color(0xFFCDE7ED)
val secondary_fixed_dim = Color(0xFFB1CBD1)
val on_secondary_fixed = Color(0xFF051F23)
val on_secondary_fixed_variant = Color(0xFF334B4F)

val tertiary_fixed = Color(0xFF9DF898)
val tertiary_fixed_dim = Color(0xFF82DB7E)
val on_tertiary_fixed = Color(0xFF002204)
val on_tertiary_fixed_variant = Color(0xFF005312)

// Dark Theme (Derived/Estimated)
val md_theme_dark_primary = Color(0xFF90D1DF)
val md_theme_dark_onPrimary = Color(0xFF00363E)
val md_theme_dark_primaryContainer = Color(0xFF004E59)
val md_theme_dark_onPrimaryContainer = Color(0xFFACEDFB)
val md_theme_dark_secondary = Color(0xFFB1CBD1)
val md_theme_dark_onSecondary = Color(0xFF1D3438)
val md_theme_dark_secondaryContainer = Color(0xFF334B4F)
val md_theme_dark_onSecondaryContainer = Color(0xFFCDE7ED)
val md_theme_dark_tertiary = Color(0xFF82DB7E)
val md_theme_dark_onTertiary = Color(0xFF003909)
val md_theme_dark_tertiaryContainer = Color(0xFF005312)
val md_theme_dark_onTertiaryContainer = Color(0xFF9DF898)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_background = Color(0xFF111718)
val md_theme_dark_onBackground = Color(0xFFE1E7E7)
val md_theme_dark_surface = Color(0xFF111718)
val md_theme_dark_onSurface = Color(0xFFE1E7E7)
val md_theme_dark_surfaceVariant = Color(0xFF3F4949)
val md_theme_dark_onSurfaceVariant = Color(0xFFBEC8C9)
val md_theme_dark_outline = Color(0xFF889294)
val md_theme_dark_inverseSurface = Color(0xFFE1E7E7)
val md_theme_dark_inverseOnSurface = Color(0xFF2C3132)
val md_theme_dark_inversePrimary = Color(0xFF206773)
